package com.aditya.weka;

import weka.classifiers.trees.J48;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.converters.ConverterUtils.DataSource;

/**
 * Tries to load a model generated by a different computer
 * Uses the j48 as classifier
 * @author aditya
 *
 */

public class LoadDifferentModel {

	public static String abs_path = "/home/aditya/CCBD_Sound_Internship/Sound_Forensics_ASR_Git/Weka";
	
	public static void main(String[] args) throws Exception{
		// load the model for testing the data
		J48 tree = (J48) weka.core.SerializationHelper.read(abs_path+"/j48_model_iris.model");
		
		DataSource source = new DataSource(abs_path+"/catj48.arff");
		Instances testdataset = source.getDataSet();
		
		testdataset.setClassIndex(testdataset.numAttributes() - 1);
		
		Instance instance = testdataset.instance(0);
		double originalVal = instance.classValue();
		String originalClass = instance.classAttribute().value((int)originalVal);
		
		double predVal = tree.classifyInstance(instance);
		String predClass = instance.classAttribute().value((int)predVal);
		
		System.out.println(originalClass+" "+predClass);
	}
}
